# Site settings
title: Ross Reinhardt
email: rreinhardt9@gmail.com
description: Ross Reinhardt's site. It's about Ruby, Rails, and life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "rreinhardt9.github.io" # the base hostname & protocol for your site
twitter_username: rtreinhardt
github_username:  rreinhardt9

# Build settings
markdown: redcarpet
