# Site settings
title: Reinhardt.io
email: rreinhardt9@gmail.com
description: Ross Reinhardt's site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "rreinhardt9.github.io" # the base hostname & protocol for your site
twitter_username: rtreinhardt
github_username:  rreinhardt9

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

exclude:
  - vendor/

gems:
 - jekyll-coffeescript
