summary: >
  Solving complex technical challenges has always been something I enjoyed.
  Currently, I am a Software Engineer working hard to transform
  great ideas into quality web applications. From front end to
  back end, I've always ready to jump in and get things done. I've developed
  new projects from a clean slate that are now in production and have also
  worked with large mature projects.

experience: >
  **Ruby**, **Rails**, and related technology are my primary strength.
  Additionally, I've gained experience visualizing data using **d3.js**. Some
  other things that I've had some exposure to include: **Elasticsearch**, **AWS**,
  **AngularJS**, **ReactJS**, data analytics in the **R language**, mobile
  app development using **Cordova**.

jobs:
  - title: Software Engineer
    company: Perceivant
    location: Indianapolis, Indiana
    start: 2015-01-01
    description: |
      - Full stack developer on a Ruby on Rails based data analytics application
      - Developed new charts based on d3.js and nvd3 library
      - Designed/ built an application to serve mini LTI lessons for consumption
        in Learning Management Systems
      - Working with ReactJS to build a responsive site for student reporting
  - title: Software Engineering Consultant
    company: Freelance
    location: Indianapolis, Indiana
    start: 2014-05-01
    end: 2015-01-01
    description: >
      - Helped clients achieve their goals mostly using Ruby, Rails, and a little
      Angular JS (with a Rails backend).
  - title: Assistant Vineyard Manager
    company: Oliver Winery
    location: Bloomington, Indiana
    start: 2012-02-01
    end: 2014-07-01
    description:
  - title: Pilot
    company: Chautauqua Airlines
    location: Indianapolis, Indiana
    start: 2007-06-01
    end: 2012-02-01
    description:
  - title: Flight Instructor
    company: Lafayette Aviation
    location: West Lafayette, Indiana
    start: 2004-12-01
    end: 2007-05-01
    description:

education:
  - date: 2007-05-01
    certification: B.S. Aviation Technology
    institution: Purdue University, West Lafayette, IN
    description: >
      GPA 3.90 (3.96 in major)
      Minors in: Aircraft Electronics and Avionics, Aircraft Turbine Engine
      Technology, Reciprocating Engine Technology, and Metallic Materials
      Technology.
